/*
 * elementproperties.c
 * ----------------------------------------
 * Contains all the arrays that define the element properties.
 * When adding a new element, you need to add it to all of these arrays as well.
 *
 * Copyright (c) 2010 Ragdoll Games
 * Copyright (c) 2010-2014 Droid Interactive
 * Copyright (c) 2010-2014 IDKJava Team
 *
 * This file is part of Particle Play.
 *
 * Particle Play is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Particle Play is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Particle Play. If not, see <http://www.gnu.org/licenses/>.
 */

//Include the global macros
#include "elementproperties.h"

// Define the names of the elements
char* baseName[] = {
    // ----Special----
    "Spawn",        // 0 = Spawn
    "Drag",         // 1 = Drag
    "Eraser",       // 2 = Eraser
    // ----Normal----
    "Sand",         // 3 = Sand
    "Water",        // 4 = Water
    "Steam",        // 5 = Steam
    "Ice",          // 6 = Ice
    "Wall",         // 7 = Wall
    "Drywall", 		// 8 = Drywall
    "Plant",        // 9 = Plant
    "Fire",         // 10 = Fire
    "Lava",			// 11 = Lava
    "Stone",        // 12 = Stone
    "Oil",          // 13 = Oil
    "C4",           // 14 = C4
    "Hydrogen",     // 15 = Hydrogen
    "Fuse",         // 16 = Fuse
    "Acid",         // 17 = Acid
    "Salt",         // 18 = Salt
    "Salt-Water",  	// 19 = Salt-Water
    "Glass",        // 20 = Glass
    "Mud",          // 21 = Mud
    "Replicator",   // 22 = Replicator
    "Coal",         // 23 = Coal
    "Ant",          // 24 = Ant
    "Gunpowder",   	// 25 = Gunpowder
    "Flies",    	// 26 = Flies
    "Wood",         // 27 = Wood
    "Termite",      // 28 = Termite
    "Insecticide", 	// 29 = Insecticide
    "Electricity",  // 30 = Electricity
    "Metal",        // 31 = Metal
};

unsigned char baseRed[] = {255,255,255,252,0,242,0,191,217,0,255,226,128,151,196,38,118,146,242,141,197,153,99,29,173,64,22,151,196,204,255,128};
unsigned char baseGreen[] = {255,255,255,201,112,242,176,191,217,176,0,107,128,71,215,38,147,208,242,180,217,102,37,27,70,64,54,71,189,192,255,128};
unsigned char baseBlue[] = {255,255,255,100,192,242,240,191,217,80,0,10,128,6,155,38,60,80,242,226,241,51,35,16,49,64,92,6,151,218,153,128};
signed char baseFallVel[] = {0,0,0,1,1,-1,0,0,0,0,-1,1,1,1,0,-1,0,1,1,1,0,1,0,1,1,1,0,0,1,1,1,0};
char baseDensity[] = {10,10,10,10,5,1,10,10,10,10,1,7,10,3,10,1,10,4,10,4,10,9,10,10,4,10,4,10,4,8,1,10};
char baseState[] = {0,0,0,0,1,2,0,0,0,0,2,1,0,1,0,2,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0};
char baseInertia[] = {255,255,255,1,1,1,255,255,255,255,1,1,3,1,255,1,255,1,1,1,255,1,255,1,1,1,1,255,1,1,1,255};
char baseStartingTemp[] = {0,0,0,0,75,151,1,0,0,0,255,255,0,0,0,100,0,0,0,0,0,0,0,0,50,0,50,0,50,0,200,0};
char baseHighestTemp[] = {255,255,255,154,150,255,75,255,200,170,255,255,200,125,200,180,150,150,255,150,255,150,255,175,175,175,175,150,175,255,255,205};
char baseLowestTemp[] = {0,0,0,0,40,100,0,0,0,0,5,180,0,0,0,31,0,0,0,60,0,0,0,0,32,0,32,0,32,0,0,0};

char baseHigherElement[] = {0,0,0,20,5,0,4,0,11,10,0,0,11,10,10,10,10,5,0,5,0,3,0,10,23,10,23,10,23,0,0,11};
char baseLowerElement[] = {0,0,0,0,6,4,0,0,0,0,23,12,0,0,0,4,0,0,0,6,0,0,0,0,3,0,3,0,3,0,0,0};

int baseSpecial[][MAX_SPECIALS] =
{
    {SPECIAL_SPAWN, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Spawn
    {SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Drag
    {SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Eraser
    {SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Sand
    {SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Water
    {SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Steam
    {SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Ice
    {SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Wall
    {SPECIAL_BREAK, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE},  //Drywall
    {SPECIAL_GROW, SPECIAL_BURN, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Plant
    {SPECIAL_HEAT, SPECIAL_LIFE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Fire
    {SPECIAL_HEAT, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Lava
    {SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Stone
    {SPECIAL_EXPLODE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Oil
    {SPECIAL_EXPLODE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //C4
    {SPECIAL_EXPLODE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Hydrogen
    {SPECIAL_BURN, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, // Fuse
    {SPECIAL_JUMP, SPECIAL_JUMP, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Acid
    {SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Salt
    {SPECIAL_CONDUCTIVE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Salt-water
    {SPECIAL_BREAK, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Glass
    {SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Mud
    {SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Replicator
    {SPECIAL_BURN, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Coal
    {SPECIAL_WANDER, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Ant
    {SPECIAL_EXPLODE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Gunpowder
    {SPECIAL_WANDER, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Flies
    {SPECIAL_BURN, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Wood
    {SPECIAL_WANDER, SPECIAL_TUNNEL, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Termite
    {SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Insecticide
    {SPECIAL_TRAIL, SPECIAL_CONDUCTABLE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE}, //Electricity
    {SPECIAL_CONDUCTIVE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE, SPECIAL_NONE} //Metal
};


//Defines the special value for each base element
int baseSpecialValue[][MAX_SPECIALS] =
{
    {SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, // SPAWN 0
    {SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, // DRAG 1
    {SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, // ERASE 2
    {SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, // SAND 3
    {SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, // WATER 4
    {SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, // STEAM 5
    {SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, // ICE 6
    {SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, // WALL 7
    {SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, // DRYWALL 8
    {4,5,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, // PLANT 9
    {20,5,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, //FIRE 10
    {3,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, //LAVA 11
    {SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, // STONE 12
    {7,3,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, // OIL 13
    {25,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, //C4 14
    {20,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, //Hydrogen 15
    {4,1,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, // FUSE 16
    {1,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, // ACID 17
    {SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, // SALT 18
    {SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, // SALTWATER 19
    {SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, // GLASS 20
    {SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, // MUD 21
    {SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, // REPLICATOR 22
    {20,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, //Coal 23
    {10,3,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, //Ant 24
    {20,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, //Gunpowder 25
    {10,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, //Flies 26
    {10,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, //Wood 27
    {5,27,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, //Termite 28
    {SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, //Insecticide 29
    {3,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET}, //Electricity 30
    {SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET,SPECIAL_VAL_UNSET} //Metal
};

